translations = {
    'en': {
        'header_text': "This utility will help you work with segmented WAV files from DiffSinger!\nSpecifically, it is designed to reformat .wav files after batch cleaning from noise, echo, etc., back to the original DiffSinger format.\nIt converts everything to mono 16-bit and can remove extra suffixes and prefixes after processing in third-party software,\nand optionally applies a smooth fade-in/fade-out and volume changes to your audio!\nAll modified files are saved to the 'converted' folder.",
        'folder_label': "Folder with WAV files:",
        'browse_button': "Browse...",
        'fade_option': "Apply fade-in/fade-out (0.15 sec)",
        'suffix_option': "Remove suffixes from file names",
        'suffix_label': "Suffixes (comma separated, e.g. _edited, _no_reverb):",
        'prefix_option': "Remove prefixes from file names",
        'prefix_label': "Prefixes (comma separated, e.g. 1_, 2_):",
        'remove_prefixes_option': "Remove prefixes before first '_' (e.g. '1_song.wav' → 'song.wav') (select count):",
        'prefix_count_label': "Number of prefixes to remove (1-3):",
        'volume_label': "Volume adjustment (dB):",
        'volume_tooltip': "Set volume change from -12dB to +12dB",
        'start_button': "Start Conversion",
        'no_files': "No .wav files in the folder.",
        'processing_done': "Processed files: ",
        'choose_folder': "Please choose a folder.",
        'error_processing': "Error processing the file: "
    },
    'ru': {
        'header_text': "Эта утилита поможет вам в работе с сегментированными WAV файлами Диффсингера!\nВ частности, она предназначена для форматирования файлов формата .wav после массовой очистки от шумов, эхо и тд в исходный формат Диффсингера.\nОна изменяет всё в формат mono 16-bit, а также может убрать лишние суффиксы после обработки в сторонних программах\nи дополнительно сделать плавный fade-in/fade-out ваших аудио!\nВсе изменённые файлы сохраняются в папку converted.",
        'folder_label': "Папка с WAV файлами:",
        'browse_button': "Обзор...",
        'fade_option': "Добавить fade-in/fade-out (0.15 сек)",
        'suffix_option': "Удалить суффиксы из имени файла",
        'suffix_label': "Суффиксы через запятую (например: _edited, _no_reverb):",
        'prefix_option': "Удалить префиксы из имени файла",
        'prefix_label': "Префиксы через запятую (например: 1_, 2_):",
        'remove_prefixes_option': "Удалить префиксы до первого '_' (например: '1_song.wav' → 'song.wav') (выберите количество):",
        'prefix_count_label': "Количество префиксов для удаления (1-3):",
        'volume_label': "Коррекция громкости (dB):",
        'volume_tooltip': "Установите изменение громкости от -12dB до +12dB",
        'start_button': "Начать конвертацию",
        'no_files': "В папке нет .wav файлов.",
        'processing_done': "Обработано файлов: ",
        'choose_folder': "Выберите папку.",
        'error_processing': "Ошибка при обработке файла: "
    },
    'fr': {
        'header_text': "Cet utilitaire vous aidera à travailler avec les fichiers WAV segmentés de DiffSinger !\nIl est spécialement conçu pour reformater les fichiers .wav après un nettoyage massif du bruit, de l’écho, etc., au format original de DiffSinger.\nIl convertit tout en mono 16 bits, peut supprimer les suffixes superflus ajoutés par d’autres logiciels,\net appliquer un fondu d’entrée/de sortie à vos fichiers audio.\nTous les fichiers modifiés sont enregistrés dans le dossier converted.",
        'folder_label': "Dossier avec des fichiers WAV:",
        'browse_button': "Parcourir...",
        'fade_option': "Appliquer fade-in/fade-out (0.15 sec)",
        'suffix_option': "Supprimer les suffixes des noms de fichiers",
        'suffix_label': "Suffixes (séparés par des virgules, par exemple: _edited, _no_reverb):",
        'prefix_option': "Supprimer les préfixes des noms de fichiers",
        'prefix_label': "Préfixes (séparés par des virgules, ex: 1_, 2_):",
        'remove_prefixes_option': "Supprimer les préfixes avant le premier '_' (ex: '1_song.wav' → 'song.wav') (choisir le nombre):",
        'prefix_count_label': "Nombre de préfixes à supprimer (1-3):",
        'volume_label': "Ajustement du volume (dB):",
        'volume_tooltip': "Définir le changement de volume de -12dB à +12dB",
        'start_button': "Commencer la conversion",
        'no_files': "Pas de fichiers .wav dans le dossier.",
        'processing_done': "Fichiers traités: ",
        'choose_folder': "Veuillez choisir un dossier.",
        'error_processing': "Erreur lors du traitement du fichier: "
    },
    'ko': {
        'header_text': "이 유틸리티는 DiffSinger의 세분화된 WAV 파일 작업을 도와줍니다!\n특히 노이즈, 에코 등을 일괄 제거한 후 .wav 파일을 DiffSinger의 원래 형식으로 다시 포맷하는 데 사용됩니다.\n모든 오디오를 모노 16비트로 변환하며, 외부 프로그램으로 처리된 파일의 불필요한 접미사를 제거하고\n부드러운 페이드 인/아웃 효과도 적용할 수 있습니다!\n모든 변경된 파일은 'converted' 폴더에 저장됩니다.",
        'folder_label': "WAV 파일이 있는 폴더:",
        'browse_button': "찾아보기...",
        'fade_option': "페이드 인/아웃 적용 (0.15초)",
        'suffix_option': "파일 이름에서 접미사 제거",
        'suffix_label': "접미사 (쉼표로 구분, 예: _edited, _no_reverb):",
        'prefix_option': "파일 이름에서 접두사 제거",
        'prefix_label': "접두사 (쉼표로 구분, 예: 1_, 2_):",
        'remove_prefixes_option': "첫 번째 '_' 이전의 접두사 제거 (예: '1_song.wav' → 'song.wav') (개수 선택):",
        'prefix_count_label': "제거할 접두사 개수 (1-3):",
        'volume_label': "볼륨 조정 (dB):",
        'volume_tooltip': "볼륨 변경 설정 (-12dB ~ +12dB)",
        'start_button': "변환 시작",
        'no_files': "폴더에 .wav 파일이 없습니다.",
        'processing_done': "처리된 파일: ",
        'choose_folder': "폴더를 선택하세요.",
        'error_processing': "파일 처리 중 오류 발생: "
    },
    'es': {
        'header_text': "¡Esta utilidad te ayudará a trabajar con archivos WAV segmentados de DiffSinger!\nEstá diseñada para volver a formatear archivos .wav tras una limpieza masiva de ruido, eco, etc., al formato original de DiffSinger.\nConvierte todo a mono 16 bits, puede eliminar sufijos innecesarios añadidos por otros programas\ny aplicar un fundido de entrada/salida suave a tu audio.\nTodos los archivos modificados se guardan en la carpeta converted.",
        'folder_label': "Carpeta con archivos WAV:",
        'browse_button': "Examinar...",
        'fade_option': "Aplicar fade-in/fade-out (0.15 seg)",
        'suffix_option': "Eliminar sufijos de los nombres de los archivos",
        'suffix_label': "Sufijos (separados por comas, p. ej.: _edited, _no_reverb):",
        'prefix_option': "Eliminar prefijos de los nombres de archivo",
        'prefix_label': "Prefijos (separados por comas, ej: 1_, 2_):",
        'remove_prefixes_option': "Eliminar prefijos antes del primer '_' (ej: '1_song.wav' → 'song.wav') (seleccionar cantidad):",
        'prefix_count_label': "Número de prefijos a eliminar (1-3):",
        'volume_label': "Ajuste de volumen (dB):",
        'volume_tooltip': "Establecer cambio de volumen de -12dB a +12dB",
        'start_button': "Comenzar conversión",
        'no_files': "No hay archivos .wav en la carpeta.",
        'processing_done': "Archivos procesados: ",
        'choose_folder': "Por favor, elija una carpeta.",
        'error_processing': "Error al procesar el archivo: "
    },
    'pt': {
        'header_text': "Este utilitário vai te ajudar a trabalhar com arquivos WAV segmentados do DiffSinger!\nÉ projetado para reformatar arquivos .wav após a limpeza em massa de ruídos, ecos, etc., de volta ao formato original do DiffSinger.\nConverte tudo para mono 16-bit, pode remover sufixos extras de programas externos\ne aplicar um fade-in/fade-out suave no seu áudio!\nTodos os arquivos modificados são salvos na pasta converted.",
        'folder_label': "Pasta com arquivos WAV:",
        'browse_button': "Procurar...",
        'fade_option': "Aplicar fade-in/fade-out (0.15 seg)",
        'suffix_option': "Remover sufixos dos nomes dos arquivos",
        'suffix_label': "Sufixos (separados por vírgulas, ex: _edited, _no_reverb):",
        'prefix_option': "Remover prefixos dos nomes dos arquivos",
        'prefix_label': "Prefixos (separados por vírgulas, ex: 1_, 2_):",
        'remove_prefixes_option': "Remover prefixos antes do primeiro '_' (ex: '1_song.wav' → 'song.wav') (selecionar quantidade):",
        'prefix_count_label': "Número de prefixos para remover (1-3):",
        'volume_label': "Ajuste de volume (dB):",
        'volume_tooltip': "Definir mudança de volume de -12dB a +12dB",
        'start_button': "Iniciar conversão",
        'no_files': "Não há arquivos .wav na pasta.",
        'processing_done': "Arquivos processados: ",
        'choose_folder': "Por favor, escolha uma pasta.",
        'error_processing': "Erro ao processar o arquivo: "
    },
    'pl': {
        'header_text': "To narzędzie pomoże ci pracować z segmentowanymi plikami WAV z DiffSingera!\nJest przeznaczone do ponownego formatowania plików .wav po masowym usuwaniu szumów, echa itp., z powrotem do oryginalnego formatu DiffSingera.\nKonwertuje wszystko do formatu mono 16-bit, może usunąć zbędne sufiksy po obróbce w zewnętrznych programach\ni opcjonalnie zastosować łagodne zanikanie (fade-in/fade-out) dźwięku.\nWszystkie zmodyfikowane pliki są zapisywane w folderze converted.",
    	'folder_label': "Folder z plikami WAV:",
    	'browse_button': "Przeglądaj...",
    	'fade_option': "Zastosuj fade-in/fade-out (0.15 sek)",
    	'suffix_option': "Usuń sufiksy z nazw plików",
    	'suffix_label': "Sufiksy (oddzielone przecinkami, np. _edited, _no_reverb):",
        'prefix_option': "Usuń przedrostki z nazw plików",
        'prefix_label': "Przedrostki (oddzielone przecinkami, np. 1_, 2_):",
        'remove_prefixes_option': "Usuń przedrostki przed pierwszym '_' (np. '1_song.wav' → 'song.wav') (wybierz liczbę):",
        'prefix_count_label': "Liczba przedrostków do usunięcia (1-3):",
        'volume_label': "Regulacja głośności (dB):",
        'volume_tooltip': "Ustaw zmianę głośności od -12dB do +12dB",
    	'start_button': "Rozpocznij konwersję",
    	'no_files': "Brak plików .wav w folderze.",
    	'processing_done': "Przetworzone pliki: ",
    	'choose_folder': "Wybierz folder.",
    	'error_processing': "Błąd podczas przetwarzania pliku: "
    },
    'zh': {
        'header_text': "此工具可帮助您处理 DiffSinger 的分段 WAV 文件！\n它专为在批量去除噪音、回声等后，将 .wav 文件重新格式化为 DiffSinger 原始格式而设计。\n它会将所有音频转换为单声道 16 位，并可删除第三方软件处理后多余的后缀，\n还可以为音频添加平滑的淡入/淡出效果！\n所有修改后的文件都会保存在 converted 文件夹中。",
        'folder_label': "包含 WAV 文件的文件夹：",
        'browse_button': "浏览...",
        'fade_option': "应用淡入/淡出 (0.15秒)",
        'suffix_option': "从文件名中移除后缀",
        'suffix_label': "后缀（以逗号分隔，例如：_edited, _no_reverb）：",
        'prefix_option': "从文件名中移除前缀",
        'prefix_label': "前缀（以逗号分隔，例如：1_, 2_）：",
        'remove_prefixes_option': "移除第一个'_'之前的前缀（例如：'1_song.wav' → 'song.wav'）（选择数量）：",
        'prefix_count_label': "要移除的前缀数量（1-3）：",
        'volume_label': "音量调整（dB）：",
        'volume_tooltip': "设置音量变化范围（-12dB 至 +12dB）",
        'start_button': "开始转换",
        'no_files': "文件夹中没有 .wav 文件。",
        'processing_done': "处理的文件：",
        'choose_folder': "请选择文件夹。",
        'error_processing': "处理文件时出错："
    },
    'ja': {
        'header_text': "このユーティリティは、DiffSinger のセグメント化された WAV ファイルの処理をサポートします！\n特に、ノイズやエコーなどを一括で除去した後、.wav ファイルを元の DiffSinger フォーマットに再フォーマットするために設計されています。\nすべてをモノラル16ビットに変換し、他のソフトで処理されたファイルの不要なサフィックスを削除し、\nオーディオにスムーズなフェードイン/フェードアウトを追加することもできます。\nすべての変更されたファイルは「converted」フォルダに保存されます。",
        'folder_label': "WAV ファイルがあるフォルダー:",
        'browse_button': "参照...",
        'fade_option': "フェードイン/フェードアウトを適用 (0.15秒)",
        'suffix_option': "ファイル名からサフィックスを削除",
        'suffix_label': "サフィックス（カンマ区切り、例：_edited, _no_reverb）：",
        'prefix_option': "ファイル名からプレフィックスを削除",
        'prefix_label': "プレフィックス（カンマ区切り、例：1_, 2_）：",
        'remove_prefixes_option': "最初の'_'の前のプレフィックスを削除（例：'1_song.wav' → 'song.wav'）（数を選択）：",
        'prefix_count_label': "削除するプレフィックスの数（1-3）：",
        'volume_label': "音量調整（dB）：",
        'volume_tooltip': "音量の変更を設定（-12dB ～ +12dB）",
        'start_button': "変換開始",
        'no_files': "フォルダーに .wav ファイルがありません。",
        'processing_done': "処理されたファイル：",
        'choose_folder': "フォルダーを選択してください。",
        'error_processing': "ファイル処理中にエラーが発生しました："
    }
}
